project:
  type: website
  output-dir: docs

website:
  title: "kwalz91.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
format:
  html:
    theme: Simplex
    css: styles.css
    toc: true

editor: visual

