project:
  type: website
  output-dir: docs

website:
  title: "kwalz91.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

