---
title: "Kevin Walz's resume"
author: Kevin Walz
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: 
      - override.css
      - resume
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
  knit: pagedown::chrome_print
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> kwalz@uni-mainz.de
- <i class="fa fa-twitter"></i> [KevinWalz18](https://twitter.com/KevinWalz18)
- <i class="fab fa-mastodon"></i> [@kwalz](https://sciences.social/@kwalz)
- <i class="fa fa-github"></i> [kwalz91](https://github.com/kwalz91)


Research Interests {#skills}
--------------------------------------------------------------------------------
- Comparative Regime Research

- Democratic Legitimacy and Democratic Deficit

- Transformation of Political Systems

- Democratic Resilience


Skills {#skills}
--------------------------------------------------------------------------------

- Comparative and Mixed-Methods Designs

- Theory-founded research

- R, SPSS


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Last updated on `r Sys.Date()`.


Main
================================================================================

Kevin Walz, M.A. {#title}
--------------------------------------------------------------------------------

### I am currently searching for a pre-/ or post-doc position from April 2024 at the latest. The exact position will depend on the progress of my dissertation and the exact regulations of the respective university.



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------


### Johannes Gutenberg University Mainz 

PhD in Political Science

N/A

2021 - 2024

Thesis: Sequences of democratic erosion - agents, opportunity structures and patterns of autocratization
(Supervisor: Professor Claudia Landwehr)


### Julius Maximilians University Würzburg

M.A. in Political and Social Sciences (1,0)

N/A

2017 - 2020

Thesis: The development of welfare states in post-socialist Central Eastern Europe: A comparative study based on partisan theory 
(Adviser: Professor Hans-Joachim Lauth; grade: 1,0)

- Comparative Politics
- Democracy Research
- Welfare States


### Julius Maximilians University Würzburg 

B.A. in Political and Social Studies (2,2)

N/A

2012 - 2016

Thesis: Rational will formation and deliberative democracy: Is political self-determination in civil society possible? 
(Adviser: Professor Michael Becker; grade: 1,7)

- Normative Political Theory
- Comparative Politics




Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### PhD student in Graduate Research Group *Resilient Institutions*

University of Mainz

N/A

2021 - 2024

- Development of theory-conceptual and empirical access to democratic resilience
- Empiric mixed-methods research on dissertation project 




Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Academic Assistant

Forum Soziale Bildung Benediktushöhe e.V. 

N/A

2020 - 2021


- Organization and conduction of educational events
- Preparation of funding applications
- Networking with schools and associations
- Supervision of interns 



Grants and Awards {data-icon=star}
--------------------------------------------------------------------------------

### PhD Scholarship 

3-year PhD scholarship funded by the Gutenberg Council for Young Researchers of the University of Mainz

N/A

2021 - 2024



Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------


### Theory and empiricism of democratic erosion

Instructor of advanced module course on democratic erosion (B.A & M.Ed.) at University of Mainz

N/A

2022 - 2023

### Tutorials on Introduction in Political Philosophy

Teaching assistant University of Würzburg

N/A

2018 - 2020


### Tutorials on Introduction to Comparative Politics

Teaching assistant at University of Würzburg

N/A

2018 - 2020


### Tutorials on Introduction to the Political System of the FRG

Teaching assistant at University of Würzburg

N/A 

2018 - 2020


Publications {data-icon=file}
--------------------------------------------------------------------------------

### A new game in town - Democratic resilience and the added value of the concept in explaining democratic survival and decline

IPP Discussion Paper Series

N/A

2022

Johannes Helgest, Lion Merten, Jana Niedringhaus, Matthias Rosenthal, **Kevin Walz**.


Work in progress {data-icon=pen}
--------------------------------------------------------------------------------

### Sequences of democratic erosion

*Book manuscript*

N/A

Forthcoming

**Kevin Walz**.


### Democratic Resilience

*Paper manuscript*

N/A

Forthcoming

Johannes Helgest, Lion Merten, Jana Niedringhaus, Matthias Rosenthal, **Kevin Walz**.



Presentations and invited talks {data-icon=paper-plane}
--------------------------------------------------------------------------------

### Typologizing processes of autocratization

Presentation at the Summer School on *Electoral Democracy in Danger?* organized by the CERIUM-FMSH Chair on Global Governance of the Sciences Po

Paris, France

July 2023

**Kevin Walz**.


### What is Anti-Pluralism, and if so, how many?

Presentation at the Anniversary Conference of the working group 
*Democracy Research* of the German Political Science Association 

Berlin, Germany

March 2023

**Kevin Walz**.


### Democratic Resilience. Potentials of a New Concept in the Empirical Study of Democracy

Presentation at the Conference *Understanding Resiliencies* of the 
Leibniz Institute for Resilience Research and the Roman-Germanic Central Museum

Mainz, Germany

November 2022

Claudia Landwehr, **Kevin Walz**.


### A new game in town - Democratic resilience and the added value of the concept in explaining democratic survival and decline

Presentation at Conference *Democracy between new crisis and new challenge*

Messina, Italy

October 2022

Johannes Helgest, Lion Merten, Jana Niedringhaus, Matthias Rosenthal, **Kevin Walz**.



Trainings {data-icon=gear}
--------------------------------------------------------------------------------

### Electoral Democracy in Danger?

5-day doctoral Summer School of the *CERIUM-FMSH Chair on Global Governance/ Scienes Po* including lectures by Markus Wagner, Sarah Birch, Natasha Wunsch, Hannah Werner, and Bert Bakker

Paris, France

July 2023


### Process-Tracing Methods

10-day methods training at *Radboud Summer School* instructed by Derek Beach and Hilde van Meedgenburg

Nijmegen, Netherlands

June 2023


### Raw texting and revising

Writing workshop of *The General Postgraduate Program (GPP)* of University of Mainz

Online

September 2022


### Academic Writing in Englisch

2-day writing workshop of *The General Postgraduate Program (GPP)* of University of Mainz

Online

August 2022


### Comparative Research Designs

5-day methods training at *Radboud Summer School* instructed by Benoit Rihoux

Nijmegen, Netherlands

June 2022


### Reading strategies and time management

Writing workshop of *The General Postgraduate Program (GPP)* of University of Mainz

Online

February 2022


### Introduction to R Programming

Workshop at *Data Science Summer School* of the Hertie School Data Science Lab

Online

July 2021


### Basic Training for Tutors

Tutoring and mentoring program *KOMPASS* of the Federal Ministry of Education and Research

Würzburg, Germany

2018


Organization of Academic Events {dat-icon=clipboard}
--------------------------------------------------------------------------------
### Orgainizing the Workshop "How to save Democracy?"

Responsibilites included conception and organization of a 2-day hybrid format workshop on contemporary challenges of democracy, as well as chairing two panels; hosted by the Graduate Research Group *Resilient Institutions*

Mainz, Germany

March 2023


### Organizing the Workshop "Democratic Resilience and its challenges"

Responsibilities included conception and organization of a 1-day hybrid workshop on democratic resilience and challenges of contemporary democracy; hosted by the Graduate Research Group *Resilient Institutions*

Mainz, Germany

September 2021



