---
title: "Research"
---

Interested in what I am working on? In the following, you find some proposals for my current projects. Most of them are related to my dissertation book project. If you are interested in one of the projects below, feel free to reach out, and I am happy to share the current working paper version, when available.

## Anti-Pluralists, Democratic Erosion, and the Breakdown Resilience of Democratic Regimes (dissertation book project)

Democracy is massively under pressure as a "third wave of Autocratization" (Lührmann & Lindberg 2019) is still rolling worldwide. Focussing contemporary Episodes of Autocratization, Scholars lately postulated the emergence of a new dominant pattern of how democracies decay and die. According to their findings, democratic regimes nowadays rarely collapse within short periods but seem to die slowly in gradual processes eroding fundamental democratic institutions and principles more often. There is evidence, that in many cases, Democratic Erosion is mainly driven by anti-pluralist actors who got voted into office and therefore, feature a minimum degree of democratic legitimacy. In most cases, Anti-Pluralists successfully change the rules of the game and transform the democratic system into an autocratic one. Only in extremely rare cases do they fail, and Democracy survives. This study examines under which circumstances the 'Defenders of Democracy' successfully stop Democratic Erosion, and what we can learn from this about the "breakdown resilience" (Boese et al. 2021) of democratic regimes.

## A three-dimensional Conceptualization of Autocratization -- How it started, how its going, and how we can systemize Research on Democratic Breakdown and Survival

The so-called "third wave of autocratization" is characterized by the slow death of democratic institutions and regimes. Those processes are mostly not contingent but the result of deliberate actions by democratically elected government. Consequently, the term democratic backsliding became the buzzword in democracy research to capture those processes conceptually and is utilized in numerous empirical studies. Nonetheless,at least two crucial questions have not been (sufficiently) addressed so far: First, we lack theoretically as well as empirically sound yardsticks to dinstiguish between disruptive and gradual Episodes. Second, we are missing elaborated frameworks to distinguish and analyze those Episodes systematically. This contribution aims to gain new insights into the specifics of the slow and fast democratic decline ending up in a precise typologization of Episodes of Democratic Regression. I plea for a three-dimensional conceptualization that takes into account the point of departure, time and outcome of Autocratization Episodes. Based on this, referring to the Episodes of Regime Transformation Dataset (ERT) I prove the empirical evidence of this conceptualization and validate initial anchors for differentiating between rather fast and rather slow forms of democratic regression. Furthermore, I demonstrate the ulitility of the conceptualization for empirical analysis using the example of the debate on 'autocratization changing its nature'. Finally, I venture an outlook on how the three-dimensional conceptualization of autocratization can be used profitably for future research on democratic regression and its causal conditions as well as mechanisms of democratic breakdown resilience.

## What is Anti-Pluralism?

Linz (1978) already associated the temperaments or ideologies of political candidates and parties with the breakdown of democratic regimes. According to his analysis, specific attitudes of political actors can be considered a predictor of undemocratic intentions and behavior in office -- and thereby ultimately also of democratic decline. It is not a coincidence that Linz's model for measuring those attitudes -- the so-called 'litmus test' -- was adopted only recently by scholars like Levitsky and Ziblatt (2018). Lührmann et al. (2021) explicitly associate the litmus test with the term Anti-Pluralism, which has become some kind of buzzword afterward. However, we can identify at least two quite fundamental shortcomings in the literature focusing on the correlation between Anti-Pluralism and autocratization. First, there is a lack of theoretical discussion on what the concept of Anti-Pluralism includes and what not. Second, there is no comprehensive theoretical reasoning that Anti-Pluralism represents a better analytical concept than other eligible isms. This contribution aims to address these shortcomings systematically.

## A new game in town: Democratic resilience and the added value of the concept in explaining democratic survival and decline

**with Johannes Helgest, Lion Merten, Jana Niedringhaus, and Matthias Rosenthal**

Resilience has become a hot topic in research due to impactful events and processes such as the global climate crisis or the Covid-19 pandemic. Nevertheless, research linking resilience with democratic processes is still spread thin. This paper aims to contribute to this research field by examining the concepts of resilience throughout various disciplines and applying them to the context of democracies, building on recent advances in this field. In our view, democratic resilience is best understood as a democratic system's capacity to process upcoming stressors. This capacity can moderate the extent to which a certain stressor poses a threat to the system. Consequently, this moderation can result in five different outcome scenarios on the regime level -- improvement, continuation, bounce back, decline, and breakdown. We argue that in comparison with traditional approaches such as democratic consolidation the concept of democratic resilience holds significant added value. This is mostly due to the concept's dynamic character and its ability to analytically include certain stressors, which enables a more fine-grained understanding of democratic survival and decline.

## 
